### PR TITLE
Added a plotting using termplotlib and requirements.txt

### PR DESCRIPTION
**Pull request by thegoodduck**
I added a plotting for better readability.

### CODE REVIEW

**Comment by thegoodduck** [comment]
@altilunium please review the code.

**Comment by altilunium** [comment]
Wait a minute… I haven't prepared a [contributing.md](https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md) file yet.

By the way, have you contributed to an open source project before?

**Comment by thegoodduck** [comment]
Its my first time contributing on an open-source project :-)

**Comment by altilunium** [comment]
To sum it up, every open-source project has a vision that the original developer had in mind. 

If your pull request aligns with that vision, the original developer will be excited and pleased to accept your contribution. However, if your idea differs from the project's direction, it might be a good idea to [fork the project and set your own direction](https://jamesdixon.wordpress.com/forking-protocol-why-when-and-how-to-fork-an-open-source-project/).

This is why the CONTRIBUTING.md file exists. It provides new contributors with insights into the original developer's vision for the project. Often, it includes specific information about the types of contributions the project is seeking and those it may not be looking for.

----
For Lacakgrak, the currently planned features are:

* Add an exit button that, when pressed, copies all statistics to the clipboard.
* For each IP address shown in the statistics, query the server's ISP information and geolocation.
* Each time the program exits, store all statistics in a SQLite database. Later, generate several new derived statistics (per-session, per-day, per-week, per-month, per-year, all-time).

Pull requests that implement these planned features will be appreciated :)

**Comment by thegoodduck** [comment]
So ok, my plan is to close this pull request and try: add a clipboard copy exit button, and ping info about the ip :-)

**Pull request closed without merging**
